# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "~/.aws/", "/home/vagrant/.aws"
  config.vm.provision :shell, path: "src/vagrant/bootstrap.sh"
end
