AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for the protected-api demo.

  '
Globals:
  Function:
    Runtime: python3.7
    Timeout: 3
Resources:
  ProtectedApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM
      AccessLogSetting: null
  AssetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sjuhasz-code/1cb5bbfdbfc809d9217c6fb367325b23
      Handler: app.assets_handler
      Runtime: python3.7
      Events:
        GetAssets:
          Type: Api
          Properties:
            RestApiId:
              Ref: ProtectedApi
            Path: /assets
            Method: get
  ProtectedApiUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - execute-api:Invoke
          Resource:
            Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ProtectedApi}/*
