AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for the protected-api demo.

Globals:
  Function:
    Runtime: python3.7
    Timeout: 3

Resources:

  ProtectedApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM
    
  AssetsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: assets/
      Handler: app.assets_handler
      Runtime: python3.7
      Events:
        GetAssets:
          Type: Api
          Properties:
            RestApiId: !Ref ProtectedApi
            Path: /assets
            Method: get

